// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: scheduling/scheduler.proto

package scheduling

import (
	context "context"
	processor "github.com/Acedyn/zorro-proto/processor"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SchedulingClient is the client API for Scheduling service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchedulingClient interface {
	// For processors to start running their commands
	RegisterProcessor(ctx context.Context, in *processor.Processor, opts ...grpc.CallOption) (*processor.Processor, error)
}

type schedulingClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulingClient(cc grpc.ClientConnInterface) SchedulingClient {
	return &schedulingClient{cc}
}

func (c *schedulingClient) RegisterProcessor(ctx context.Context, in *processor.Processor, opts ...grpc.CallOption) (*processor.Processor, error) {
	out := new(processor.Processor)
	err := c.cc.Invoke(ctx, "/zorro.Scheduling/RegisterProcessor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulingServer is the server API for Scheduling service.
// All implementations must embed UnimplementedSchedulingServer
// for forward compatibility
type SchedulingServer interface {
	// For processors to start running their commands
	RegisterProcessor(context.Context, *processor.Processor) (*processor.Processor, error)
	mustEmbedUnimplementedSchedulingServer()
}

// UnimplementedSchedulingServer must be embedded to have forward compatible implementations.
type UnimplementedSchedulingServer struct {
}

func (UnimplementedSchedulingServer) RegisterProcessor(context.Context, *processor.Processor) (*processor.Processor, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterProcessor not implemented")
}
func (UnimplementedSchedulingServer) mustEmbedUnimplementedSchedulingServer() {}

// UnsafeSchedulingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulingServer will
// result in compilation errors.
type UnsafeSchedulingServer interface {
	mustEmbedUnimplementedSchedulingServer()
}

func RegisterSchedulingServer(s grpc.ServiceRegistrar, srv SchedulingServer) {
	s.RegisterService(&Scheduling_ServiceDesc, srv)
}

func _Scheduling_RegisterProcessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(processor.Processor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServer).RegisterProcessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zorro.Scheduling/RegisterProcessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServer).RegisterProcessor(ctx, req.(*processor.Processor))
	}
	return interceptor(ctx, in, info, handler)
}

// Scheduling_ServiceDesc is the grpc.ServiceDesc for Scheduling service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scheduling_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zorro.Scheduling",
	HandlerType: (*SchedulingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterProcessor",
			Handler:    _Scheduling_RegisterProcessor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scheduling/scheduler.proto",
}
