# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduling/scheduler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tools import command_pb2 as tools_dot_command__pb2
from processor import processor_pb2 as processor_dot_processor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ascheduling/scheduler.proto\x12\x05zorro\x1a\x13tools/command.proto\x1a\x19processor/processor.proto\"\x9e\x01\n\x16processorCommunication\x12+\n\x0e\x63ommand_update\x18\x01 \x01(\x0b\x32\x0e.zorro.CommandH\x00\x88\x01\x01\x12/\n\x10processor_update\x18\x02 \x01(\x0b\x32\x10.zorro.ProcessorH\x01\x88\x01\x01\x42\x11\n\x0f_command_updateB\x13\n\x11_processor_update2E\n\nScheduling\x12\x37\n\x11RegisterProcessor\x12\x10.zorro.Processor\x1a\x10.zorro.ProcessorB*Z(github.com/Acedyn/zorro-proto/schedulingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scheduling.scheduler_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z(github.com/Acedyn/zorro-proto/scheduling'
  _globals['_PROCESSORCOMMUNICATION']._serialized_start=86
  _globals['_PROCESSORCOMMUNICATION']._serialized_end=244
  _globals['_SCHEDULING']._serialized_start=246
  _globals['_SCHEDULING']._serialized_end=315
# @@protoc_insertion_point(module_scope)
