# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zorroprotos/config/fs_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"zorroprotos/config/fs_config.proto\x12\x05zorro\"\x0c\n\nOsFsConfig\"!\n\x11IndexedDbFsConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x10\n\x0eMemoryFsConfig\"\xba\x01\n\x10\x46ileSystemConfig\x12#\n\x04type\x18\x01 \x01(\x0e\x32\x15.zorro.FileSystemType\x12\x1f\n\x02os\x18\x02 \x01(\x0b\x32\x11.zorro.OsFsConfigH\x00\x12-\n\tindexedDb\x18\x03 \x01(\x0b\x32\x18.zorro.IndexedDbFsConfigH\x00\x12\'\n\x06memory\x18\x04 \x01(\x0b\x32\x15.zorro.MemoryFsConfigH\x00\x42\x08\n\x06\x63onfig\"B\n\x11\x46ileSystemsConfig\x12-\n\x0c\x66ile_systems\x18\x01 \x03(\x0b\x32\x17.zorro.FileSystemConfig*3\n\x0e\x46ileSystemType\x12\x06\n\x02Os\x10\x00\x12\r\n\tIndexedDb\x10\x01\x12\n\n\x06Memory\x10\x02\x42\x32Z0github.com/Acedyn/zorro-proto/zorroprotos/configb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zorroprotos.config.fs_config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z0github.com/Acedyn/zorro-proto/zorroprotos/config'
  _globals['_FILESYSTEMTYPE']._serialized_start=369
  _globals['_FILESYSTEMTYPE']._serialized_end=420
  _globals['_OSFSCONFIG']._serialized_start=45
  _globals['_OSFSCONFIG']._serialized_end=57
  _globals['_INDEXEDDBFSCONFIG']._serialized_start=59
  _globals['_INDEXEDDBFSCONFIG']._serialized_end=92
  _globals['_MEMORYFSCONFIG']._serialized_start=94
  _globals['_MEMORYFSCONFIG']._serialized_end=110
  _globals['_FILESYSTEMCONFIG']._serialized_start=113
  _globals['_FILESYSTEMCONFIG']._serialized_end=299
  _globals['_FILESYSTEMSCONFIG']._serialized_start=301
  _globals['_FILESYSTEMSCONFIG']._serialized_end=367
# @@protoc_insertion_point(module_scope)
