// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.2
// source: zorroprotos/config/fs_config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// List all the available languages
type FileSystemType int32

const (
	FileSystemType_Os        FileSystemType = 0
	FileSystemType_IndexedDb FileSystemType = 1
	FileSystemType_Memory    FileSystemType = 2
)

// Enum value maps for FileSystemType.
var (
	FileSystemType_name = map[int32]string{
		0: "Os",
		1: "IndexedDb",
		2: "Memory",
	}
	FileSystemType_value = map[string]int32{
		"Os":        0,
		"IndexedDb": 1,
		"Memory":    2,
	}
)

func (x FileSystemType) Enum() *FileSystemType {
	p := new(FileSystemType)
	*p = x
	return p
}

func (x FileSystemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileSystemType) Descriptor() protoreflect.EnumDescriptor {
	return file_zorroprotos_config_fs_config_proto_enumTypes[0].Descriptor()
}

func (FileSystemType) Type() protoreflect.EnumType {
	return &file_zorroprotos_config_fs_config_proto_enumTypes[0]
}

func (x FileSystemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileSystemType.Descriptor instead.
func (FileSystemType) EnumDescriptor() ([]byte, []int) {
	return file_zorroprotos_config_fs_config_proto_rawDescGZIP(), []int{0}
}

// Config for the OS file system
type OsFsConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OsFsConfig) Reset() {
	*x = OsFsConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zorroprotos_config_fs_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OsFsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OsFsConfig) ProtoMessage() {}

func (x *OsFsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_zorroprotos_config_fs_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OsFsConfig.ProtoReflect.Descriptor instead.
func (*OsFsConfig) Descriptor() ([]byte, []int) {
	return file_zorroprotos_config_fs_config_proto_rawDescGZIP(), []int{0}
}

// Config for the indexed DB file system
type IndexedDbFsConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *IndexedDbFsConfig) Reset() {
	*x = IndexedDbFsConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zorroprotos_config_fs_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexedDbFsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexedDbFsConfig) ProtoMessage() {}

func (x *IndexedDbFsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_zorroprotos_config_fs_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexedDbFsConfig.ProtoReflect.Descriptor instead.
func (*IndexedDbFsConfig) Descriptor() ([]byte, []int) {
	return file_zorroprotos_config_fs_config_proto_rawDescGZIP(), []int{1}
}

func (x *IndexedDbFsConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Config for the in memory file system
type MemoryFsConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MemoryFsConfig) Reset() {
	*x = MemoryFsConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zorroprotos_config_fs_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemoryFsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryFsConfig) ProtoMessage() {}

func (x *MemoryFsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_zorroprotos_config_fs_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryFsConfig.ProtoReflect.Descriptor instead.
func (*MemoryFsConfig) Descriptor() ([]byte, []int) {
	return file_zorroprotos_config_fs_config_proto_rawDescGZIP(), []int{2}
}

// Config for a selected file system
type FileSystemConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type FileSystemType `protobuf:"varint,1,opt,name=type,proto3,enum=zorro.FileSystemType" json:"type,omitempty"`
	// Types that are assignable to Config:
	//
	//	*FileSystemConfig_Os
	//	*FileSystemConfig_IndexedDb
	//	*FileSystemConfig_Memory
	Config isFileSystemConfig_Config `protobuf_oneof:"config"`
}

func (x *FileSystemConfig) Reset() {
	*x = FileSystemConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zorroprotos_config_fs_config_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileSystemConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSystemConfig) ProtoMessage() {}

func (x *FileSystemConfig) ProtoReflect() protoreflect.Message {
	mi := &file_zorroprotos_config_fs_config_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSystemConfig.ProtoReflect.Descriptor instead.
func (*FileSystemConfig) Descriptor() ([]byte, []int) {
	return file_zorroprotos_config_fs_config_proto_rawDescGZIP(), []int{3}
}

func (x *FileSystemConfig) GetType() FileSystemType {
	if x != nil {
		return x.Type
	}
	return FileSystemType_Os
}

func (m *FileSystemConfig) GetConfig() isFileSystemConfig_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (x *FileSystemConfig) GetOs() *OsFsConfig {
	if x, ok := x.GetConfig().(*FileSystemConfig_Os); ok {
		return x.Os
	}
	return nil
}

func (x *FileSystemConfig) GetIndexedDb() *IndexedDbFsConfig {
	if x, ok := x.GetConfig().(*FileSystemConfig_IndexedDb); ok {
		return x.IndexedDb
	}
	return nil
}

func (x *FileSystemConfig) GetMemory() *MemoryFsConfig {
	if x, ok := x.GetConfig().(*FileSystemConfig_Memory); ok {
		return x.Memory
	}
	return nil
}

type isFileSystemConfig_Config interface {
	isFileSystemConfig_Config()
}

type FileSystemConfig_Os struct {
	Os *OsFsConfig `protobuf:"bytes,2,opt,name=os,proto3,oneof"`
}

type FileSystemConfig_IndexedDb struct {
	IndexedDb *IndexedDbFsConfig `protobuf:"bytes,3,opt,name=indexedDb,proto3,oneof"`
}

type FileSystemConfig_Memory struct {
	Memory *MemoryFsConfig `protobuf:"bytes,4,opt,name=memory,proto3,oneof"`
}

func (*FileSystemConfig_Os) isFileSystemConfig_Config() {}

func (*FileSystemConfig_IndexedDb) isFileSystemConfig_Config() {}

func (*FileSystemConfig_Memory) isFileSystemConfig_Config() {}

// Config related to the user's preferences
type FileSystemsConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileSystems map[string]*FileSystemConfig `protobuf:"bytes,1,rep,name=file_systems,json=fileSystems,proto3" json:"file_systems,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *FileSystemsConfig) Reset() {
	*x = FileSystemsConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zorroprotos_config_fs_config_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileSystemsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSystemsConfig) ProtoMessage() {}

func (x *FileSystemsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_zorroprotos_config_fs_config_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSystemsConfig.ProtoReflect.Descriptor instead.
func (*FileSystemsConfig) Descriptor() ([]byte, []int) {
	return file_zorroprotos_config_fs_config_proto_rawDescGZIP(), []int{4}
}

func (x *FileSystemsConfig) GetFileSystems() map[string]*FileSystemConfig {
	if x != nil {
		return x.FileSystems
	}
	return nil
}

var File_zorroprotos_config_fs_config_proto protoreflect.FileDescriptor

var file_zorroprotos_config_fs_config_proto_rawDesc = []byte{
	0x0a, 0x22, 0x7a, 0x6f, 0x72, 0x72, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2f, 0x66, 0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x7a, 0x6f, 0x72, 0x72, 0x6f, 0x22, 0x0c, 0x0a, 0x0a, 0x4f,
	0x73, 0x46, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x27, 0x0a, 0x11, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x65, 0x64, 0x44, 0x62, 0x46, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x46, 0x73, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x22, 0xd7, 0x01, 0x0a, 0x10, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x29, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x7a, 0x6f, 0x72, 0x72, 0x6f, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x7a, 0x6f, 0x72, 0x72, 0x6f, 0x2e, 0x4f, 0x73, 0x46, 0x73, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x38, 0x0a, 0x09, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x65, 0x64, 0x44, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x7a,
	0x6f, 0x72, 0x72, 0x6f, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x64, 0x44, 0x62, 0x46, 0x73,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x09, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65,
	0x64, 0x44, 0x62, 0x12, 0x2f, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x7a, 0x6f, 0x72, 0x72, 0x6f, 0x2e, 0x4d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x46, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x06, 0x6d, 0x65,
	0x6d, 0x6f, 0x72, 0x79, 0x42, 0x08, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0xba,
	0x01, 0x0a, 0x11, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x4c, 0x0a, 0x0c, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x7a, 0x6f, 0x72,
	0x72, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x73, 0x1a, 0x57, 0x0a, 0x10, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x7a, 0x6f, 0x72, 0x72, 0x6f, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x2a, 0x33, 0x0a, 0x0e, 0x46,
	0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x06, 0x0a,
	0x02, 0x4f, 0x73, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x64,
	0x44, 0x62, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x10, 0x02,
	0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41,
	0x63, 0x65, 0x64, 0x79, 0x6e, 0x2f, 0x7a, 0x6f, 0x72, 0x72, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x7a, 0x6f, 0x72, 0x72, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zorroprotos_config_fs_config_proto_rawDescOnce sync.Once
	file_zorroprotos_config_fs_config_proto_rawDescData = file_zorroprotos_config_fs_config_proto_rawDesc
)

func file_zorroprotos_config_fs_config_proto_rawDescGZIP() []byte {
	file_zorroprotos_config_fs_config_proto_rawDescOnce.Do(func() {
		file_zorroprotos_config_fs_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_zorroprotos_config_fs_config_proto_rawDescData)
	})
	return file_zorroprotos_config_fs_config_proto_rawDescData
}

var file_zorroprotos_config_fs_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_zorroprotos_config_fs_config_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_zorroprotos_config_fs_config_proto_goTypes = []interface{}{
	(FileSystemType)(0),       // 0: zorro.FileSystemType
	(*OsFsConfig)(nil),        // 1: zorro.OsFsConfig
	(*IndexedDbFsConfig)(nil), // 2: zorro.IndexedDbFsConfig
	(*MemoryFsConfig)(nil),    // 3: zorro.MemoryFsConfig
	(*FileSystemConfig)(nil),  // 4: zorro.FileSystemConfig
	(*FileSystemsConfig)(nil), // 5: zorro.FileSystemsConfig
	nil,                       // 6: zorro.FileSystemsConfig.FileSystemsEntry
}
var file_zorroprotos_config_fs_config_proto_depIdxs = []int32{
	0, // 0: zorro.FileSystemConfig.type:type_name -> zorro.FileSystemType
	1, // 1: zorro.FileSystemConfig.os:type_name -> zorro.OsFsConfig
	2, // 2: zorro.FileSystemConfig.indexedDb:type_name -> zorro.IndexedDbFsConfig
	3, // 3: zorro.FileSystemConfig.memory:type_name -> zorro.MemoryFsConfig
	6, // 4: zorro.FileSystemsConfig.file_systems:type_name -> zorro.FileSystemsConfig.FileSystemsEntry
	4, // 5: zorro.FileSystemsConfig.FileSystemsEntry.value:type_name -> zorro.FileSystemConfig
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_zorroprotos_config_fs_config_proto_init() }
func file_zorroprotos_config_fs_config_proto_init() {
	if File_zorroprotos_config_fs_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zorroprotos_config_fs_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OsFsConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zorroprotos_config_fs_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexedDbFsConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zorroprotos_config_fs_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemoryFsConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zorroprotos_config_fs_config_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileSystemConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zorroprotos_config_fs_config_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileSystemsConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_zorroprotos_config_fs_config_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*FileSystemConfig_Os)(nil),
		(*FileSystemConfig_IndexedDb)(nil),
		(*FileSystemConfig_Memory)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zorroprotos_config_fs_config_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zorroprotos_config_fs_config_proto_goTypes,
		DependencyIndexes: file_zorroprotos_config_fs_config_proto_depIdxs,
		EnumInfos:         file_zorroprotos_config_fs_config_proto_enumTypes,
		MessageInfos:      file_zorroprotos_config_fs_config_proto_msgTypes,
	}.Build()
	File_zorroprotos_config_fs_config_proto = out.File
	file_zorroprotos_config_fs_config_proto_rawDesc = nil
	file_zorroprotos_config_fs_config_proto_goTypes = nil
	file_zorroprotos_config_fs_config_proto_depIdxs = nil
}
