// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: zorroprotos/config/plugin_config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Config related to the plugins
type PluginConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The list of plugins that will be required all the time
	DefaultRequire []string `protobuf:"bytes,1,rep,name=default_require,json=defaultRequire,proto3" json:"default_require,omitempty"`
	// List of plugin repository addresses
	Repos []string `protobuf:"bytes,2,rep,name=repos,proto3" json:"repos,omitempty"`
}

func (x *PluginConfig) Reset() {
	*x = PluginConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zorroprotos_config_plugin_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginConfig) ProtoMessage() {}

func (x *PluginConfig) ProtoReflect() protoreflect.Message {
	mi := &file_zorroprotos_config_plugin_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginConfig.ProtoReflect.Descriptor instead.
func (*PluginConfig) Descriptor() ([]byte, []int) {
	return file_zorroprotos_config_plugin_config_proto_rawDescGZIP(), []int{0}
}

func (x *PluginConfig) GetDefaultRequire() []string {
	if x != nil {
		return x.DefaultRequire
	}
	return nil
}

func (x *PluginConfig) GetRepos() []string {
	if x != nil {
		return x.Repos
	}
	return nil
}

var File_zorroprotos_config_plugin_config_proto protoreflect.FileDescriptor

var file_zorroprotos_config_plugin_config_proto_rawDesc = []byte{
	0x0a, 0x26, 0x7a, 0x6f, 0x72, 0x72, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x7a, 0x6f, 0x72, 0x72, 0x6f, 0x22,
	0x4d, 0x0a, 0x0c, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x27, 0x0a, 0x0f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6f,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x42, 0x32,
	0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x63, 0x65,
	0x64, 0x79, 0x6e, 0x2f, 0x7a, 0x6f, 0x72, 0x72, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x7a, 0x6f, 0x72, 0x72, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zorroprotos_config_plugin_config_proto_rawDescOnce sync.Once
	file_zorroprotos_config_plugin_config_proto_rawDescData = file_zorroprotos_config_plugin_config_proto_rawDesc
)

func file_zorroprotos_config_plugin_config_proto_rawDescGZIP() []byte {
	file_zorroprotos_config_plugin_config_proto_rawDescOnce.Do(func() {
		file_zorroprotos_config_plugin_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_zorroprotos_config_plugin_config_proto_rawDescData)
	})
	return file_zorroprotos_config_plugin_config_proto_rawDescData
}

var file_zorroprotos_config_plugin_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_zorroprotos_config_plugin_config_proto_goTypes = []interface{}{
	(*PluginConfig)(nil), // 0: zorro.PluginConfig
}
var file_zorroprotos_config_plugin_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zorroprotos_config_plugin_config_proto_init() }
func file_zorroprotos_config_plugin_config_proto_init() {
	if File_zorroprotos_config_plugin_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zorroprotos_config_plugin_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zorroprotos_config_plugin_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zorroprotos_config_plugin_config_proto_goTypes,
		DependencyIndexes: file_zorroprotos_config_plugin_config_proto_depIdxs,
		MessageInfos:      file_zorroprotos_config_plugin_config_proto_msgTypes,
	}.Build()
	File_zorroprotos_config_plugin_config_proto = out.File
	file_zorroprotos_config_plugin_config_proto_rawDesc = nil
	file_zorroprotos_config_plugin_config_proto_goTypes = nil
	file_zorroprotos_config_plugin_config_proto_depIdxs = nil
}
