// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: zorroprotos/tools/socket.proto

package tools

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A socket acts as a payload for an input/output between two tools
type Socket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The raw data can then be casted into a different datatype
	//
	// Types that are assignable to Raw:
	//
	//	*Socket_RawString
	//	*Socket_RawInteger
	//	*Socket_RawNumber
	//	*Socket_RawBinary
	Raw isSocket_Raw `protobuf_oneof:"raw"`
	// Indicator for the processor to cast the raw data into any datatype
	Cast string `protobuf:"bytes,5,opt,name=cast,proto3" json:"cast,omitempty"`
}

func (x *Socket) Reset() {
	*x = Socket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zorroprotos_tools_socket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Socket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Socket) ProtoMessage() {}

func (x *Socket) ProtoReflect() protoreflect.Message {
	mi := &file_zorroprotos_tools_socket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Socket.ProtoReflect.Descriptor instead.
func (*Socket) Descriptor() ([]byte, []int) {
	return file_zorroprotos_tools_socket_proto_rawDescGZIP(), []int{0}
}

func (m *Socket) GetRaw() isSocket_Raw {
	if m != nil {
		return m.Raw
	}
	return nil
}

func (x *Socket) GetRawString() string {
	if x, ok := x.GetRaw().(*Socket_RawString); ok {
		return x.RawString
	}
	return ""
}

func (x *Socket) GetRawInteger() int32 {
	if x, ok := x.GetRaw().(*Socket_RawInteger); ok {
		return x.RawInteger
	}
	return 0
}

func (x *Socket) GetRawNumber() float32 {
	if x, ok := x.GetRaw().(*Socket_RawNumber); ok {
		return x.RawNumber
	}
	return 0
}

func (x *Socket) GetRawBinary() []byte {
	if x, ok := x.GetRaw().(*Socket_RawBinary); ok {
		return x.RawBinary
	}
	return nil
}

func (x *Socket) GetCast() string {
	if x != nil {
		return x.Cast
	}
	return ""
}

type isSocket_Raw interface {
	isSocket_Raw()
}

type Socket_RawString struct {
	RawString string `protobuf:"bytes,1,opt,name=raw_string,json=rawString,proto3,oneof"`
}

type Socket_RawInteger struct {
	RawInteger int32 `protobuf:"varint,2,opt,name=raw_integer,json=rawInteger,proto3,oneof"`
}

type Socket_RawNumber struct {
	RawNumber float32 `protobuf:"fixed32,3,opt,name=raw_number,json=rawNumber,proto3,oneof"`
}

type Socket_RawBinary struct {
	RawBinary []byte `protobuf:"bytes,4,opt,name=raw_binary,json=rawBinary,proto3,oneof"`
}

func (*Socket_RawString) isSocket_Raw() {}

func (*Socket_RawInteger) isSocket_Raw() {}

func (*Socket_RawNumber) isSocket_Raw() {}

func (*Socket_RawBinary) isSocket_Raw() {}

var File_zorroprotos_tools_socket_proto protoreflect.FileDescriptor

var file_zorroprotos_tools_socket_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x7a, 0x6f, 0x72, 0x72, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x74, 0x6f,
	0x6f, 0x6c, 0x73, 0x2f, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x7a, 0x6f, 0x72, 0x72, 0x6f, 0x22, 0xa9, 0x01, 0x0a, 0x06, 0x53, 0x6f, 0x63, 0x6b,
	0x65, 0x74, 0x12, 0x1f, 0x0a, 0x0a, 0x72, 0x61, 0x77, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x72, 0x61, 0x77, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x12, 0x21, 0x0a, 0x0b, 0x72, 0x61, 0x77, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x67,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x61, 0x77, 0x49,
	0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0a, 0x72, 0x61, 0x77, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x09, 0x72, 0x61,
	0x77, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0a, 0x72, 0x61, 0x77, 0x5f, 0x62,
	0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x72,
	0x61, 0x77, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x73, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x61, 0x73, 0x74, 0x42, 0x05, 0x0a, 0x03,
	0x72, 0x61, 0x77, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x41, 0x63, 0x65, 0x64, 0x79, 0x6e, 0x2f, 0x7a, 0x6f, 0x72, 0x72, 0x6f, 0x2d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x7a, 0x6f, 0x72, 0x72, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zorroprotos_tools_socket_proto_rawDescOnce sync.Once
	file_zorroprotos_tools_socket_proto_rawDescData = file_zorroprotos_tools_socket_proto_rawDesc
)

func file_zorroprotos_tools_socket_proto_rawDescGZIP() []byte {
	file_zorroprotos_tools_socket_proto_rawDescOnce.Do(func() {
		file_zorroprotos_tools_socket_proto_rawDescData = protoimpl.X.CompressGZIP(file_zorroprotos_tools_socket_proto_rawDescData)
	})
	return file_zorroprotos_tools_socket_proto_rawDescData
}

var file_zorroprotos_tools_socket_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_zorroprotos_tools_socket_proto_goTypes = []interface{}{
	(*Socket)(nil), // 0: zorro.Socket
}
var file_zorroprotos_tools_socket_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zorroprotos_tools_socket_proto_init() }
func file_zorroprotos_tools_socket_proto_init() {
	if File_zorroprotos_tools_socket_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zorroprotos_tools_socket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Socket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_zorroprotos_tools_socket_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Socket_RawString)(nil),
		(*Socket_RawInteger)(nil),
		(*Socket_RawNumber)(nil),
		(*Socket_RawBinary)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zorroprotos_tools_socket_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zorroprotos_tools_socket_proto_goTypes,
		DependencyIndexes: file_zorroprotos_tools_socket_proto_depIdxs,
		MessageInfos:      file_zorroprotos_tools_socket_proto_msgTypes,
	}.Build()
	File_zorroprotos_tools_socket_proto = out.File
	file_zorroprotos_tools_socket_proto_rawDesc = nil
	file_zorroprotos_tools_socket_proto_goTypes = nil
	file_zorroprotos_tools_socket_proto_depIdxs = nil
}
