# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/plugin.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from processor import processor_pb2 as processor_dot_processor__pb2
from plugin import plugin_env_pb2 as plugin_dot_plugin__env__pb2
from plugin import plugin_tools_pb2 as plugin_dot_plugin__tools__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13plugin/plugin.proto\x12\x05zorro\x1a\x19processor/processor.proto\x1a\x17plugin/plugin_env.proto\x1a\x19plugin/plugin_tools.proto\"\xad\x02\n\x06Plugin\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x12\n\x05label\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04path\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x0f\n\x07require\x18\x05 \x03(\t\x12#\n\x03\x65nv\x18\x06 \x03(\x0b\x32\x16.zorro.Plugin.EnvEntry\x12&\n\x05tools\x18\x07 \x01(\x0b\x32\x12.zorro.PluginToolsH\x02\x88\x01\x01\x12$\n\nprocessors\x18\x08 \x03(\x0b\x32\x10.zorro.Processor\x1a<\n\x08\x45nvEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.zorro.PluginEnv:\x02\x38\x01\x42\x08\n\x06_labelB\x07\n\x05_pathB\x08\n\x06_toolsB&Z$github.com/Acedyn/zorro-proto/pluginb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugin.plugin_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z$github.com/Acedyn/zorro-proto/plugin'
  _PLUGIN_ENVENTRY._options = None
  _PLUGIN_ENVENTRY._serialized_options = b'8\001'
  _globals['_PLUGIN']._serialized_start=110
  _globals['_PLUGIN']._serialized_end=411
  _globals['_PLUGIN_ENVENTRY']._serialized_start=322
  _globals['_PLUGIN_ENVENTRY']._serialized_end=382
# @@protoc_insertion_point(module_scope)
