# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: context/context.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from plugin import plugin_pb2 as plugin_dot_plugin__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ontext/context.proto\x12\x05zorro\x1a\x13plugin/plugin.proto\")\n\x07\x43ontext\x12\x1e\n\x07plugins\x18\x01 \x03(\x0b\x32\r.zorro.PluginB\'Z%github.com/Acedyn/zorro-proto/contextb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'context.context_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z%github.com/Acedyn/zorro-proto/context'
  _globals['_CONTEXT']._serialized_start=53
  _globals['_CONTEXT']._serialized_end=94
# @@protoc_insertion_point(module_scope)
