// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.2
// source: zorroprotos/plugin/plugin_tools.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Specify where to look for tools of a category
type ToolsDeclaration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path     string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *ToolsDeclaration) Reset() {
	*x = ToolsDeclaration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zorroprotos_plugin_plugin_tools_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToolsDeclaration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolsDeclaration) ProtoMessage() {}

func (x *ToolsDeclaration) ProtoReflect() protoreflect.Message {
	mi := &file_zorroprotos_plugin_plugin_tools_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolsDeclaration.ProtoReflect.Descriptor instead.
func (*ToolsDeclaration) Descriptor() ([]byte, []int) {
	return file_zorroprotos_plugin_plugin_tools_proto_rawDescGZIP(), []int{0}
}

func (x *ToolsDeclaration) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ToolsDeclaration) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

// Where to look for tool declarations
type PluginTools struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commands []*ToolsDeclaration `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	Actions  []*ToolsDeclaration `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	Hooks    []*ToolsDeclaration `protobuf:"bytes,3,rep,name=hooks,proto3" json:"hooks,omitempty"`
	Widgets  []*ToolsDeclaration `protobuf:"bytes,4,rep,name=widgets,proto3" json:"widgets,omitempty"`
}

func (x *PluginTools) Reset() {
	*x = PluginTools{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zorroprotos_plugin_plugin_tools_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginTools) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginTools) ProtoMessage() {}

func (x *PluginTools) ProtoReflect() protoreflect.Message {
	mi := &file_zorroprotos_plugin_plugin_tools_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginTools.ProtoReflect.Descriptor instead.
func (*PluginTools) Descriptor() ([]byte, []int) {
	return file_zorroprotos_plugin_plugin_tools_proto_rawDescGZIP(), []int{1}
}

func (x *PluginTools) GetCommands() []*ToolsDeclaration {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *PluginTools) GetActions() []*ToolsDeclaration {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *PluginTools) GetHooks() []*ToolsDeclaration {
	if x != nil {
		return x.Hooks
	}
	return nil
}

func (x *PluginTools) GetWidgets() []*ToolsDeclaration {
	if x != nil {
		return x.Widgets
	}
	return nil
}

var File_zorroprotos_plugin_plugin_tools_proto protoreflect.FileDescriptor

var file_zorroprotos_plugin_plugin_tools_proto_rawDesc = []byte{
	0x0a, 0x25, 0x7a, 0x6f, 0x72, 0x72, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x74, 0x6f, 0x6f, 0x6c,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x7a, 0x6f, 0x72, 0x72, 0x6f, 0x22, 0x42,
	0x0a, 0x10, 0x54, 0x6f, 0x6f, 0x6c, 0x73, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x22, 0xd7, 0x01, 0x0a, 0x0b, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x54, 0x6f, 0x6f,
	0x6c, 0x73, 0x12, 0x33, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x7a, 0x6f, 0x72, 0x72, 0x6f, 0x2e, 0x54, 0x6f, 0x6f,
	0x6c, 0x73, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x12, 0x31, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x7a, 0x6f, 0x72, 0x72, 0x6f,
	0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x73, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2d, 0x0a, 0x05, 0x68, 0x6f,
	0x6f, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x7a, 0x6f, 0x72, 0x72,
	0x6f, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x73, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x05, 0x68, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x31, 0x0a, 0x07, 0x77, 0x69, 0x64,
	0x67, 0x65, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x7a, 0x6f, 0x72,
	0x72, 0x6f, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x73, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x07, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x73, 0x42, 0x32, 0x5a, 0x30,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x63, 0x65, 0x64, 0x79,
	0x6e, 0x2f, 0x7a, 0x6f, 0x72, 0x72, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x7a, 0x6f,
	0x72, 0x72, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zorroprotos_plugin_plugin_tools_proto_rawDescOnce sync.Once
	file_zorroprotos_plugin_plugin_tools_proto_rawDescData = file_zorroprotos_plugin_plugin_tools_proto_rawDesc
)

func file_zorroprotos_plugin_plugin_tools_proto_rawDescGZIP() []byte {
	file_zorroprotos_plugin_plugin_tools_proto_rawDescOnce.Do(func() {
		file_zorroprotos_plugin_plugin_tools_proto_rawDescData = protoimpl.X.CompressGZIP(file_zorroprotos_plugin_plugin_tools_proto_rawDescData)
	})
	return file_zorroprotos_plugin_plugin_tools_proto_rawDescData
}

var file_zorroprotos_plugin_plugin_tools_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_zorroprotos_plugin_plugin_tools_proto_goTypes = []interface{}{
	(*ToolsDeclaration)(nil), // 0: zorro.ToolsDeclaration
	(*PluginTools)(nil),      // 1: zorro.PluginTools
}
var file_zorroprotos_plugin_plugin_tools_proto_depIdxs = []int32{
	0, // 0: zorro.PluginTools.commands:type_name -> zorro.ToolsDeclaration
	0, // 1: zorro.PluginTools.actions:type_name -> zorro.ToolsDeclaration
	0, // 2: zorro.PluginTools.hooks:type_name -> zorro.ToolsDeclaration
	0, // 3: zorro.PluginTools.widgets:type_name -> zorro.ToolsDeclaration
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_zorroprotos_plugin_plugin_tools_proto_init() }
func file_zorroprotos_plugin_plugin_tools_proto_init() {
	if File_zorroprotos_plugin_plugin_tools_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zorroprotos_plugin_plugin_tools_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToolsDeclaration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zorroprotos_plugin_plugin_tools_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginTools); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zorroprotos_plugin_plugin_tools_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zorroprotos_plugin_plugin_tools_proto_goTypes,
		DependencyIndexes: file_zorroprotos_plugin_plugin_tools_proto_depIdxs,
		MessageInfos:      file_zorroprotos_plugin_plugin_tools_proto_msgTypes,
	}.Build()
	File_zorroprotos_plugin_plugin_tools_proto = out.File
	file_zorroprotos_plugin_plugin_tools_proto_rawDesc = nil
	file_zorroprotos_plugin_plugin_tools_proto_goTypes = nil
	file_zorroprotos_plugin_plugin_tools_proto_depIdxs = nil
}
