# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config/plugin_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63onfig/plugin_config.proto\x12\x05zorro\"B\n\x0cPluginConfig\x12\x17\n\x0f\x64\x65\x66\x61ult_require\x18\x01 \x03(\t\x12\x19\n\x11plugin_repo_paths\x18\x02 \x03(\tB&Z$github.com/Acedyn/zorro-proto/configb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config.plugin_config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z$github.com/Acedyn/zorro-proto/config'
  _globals['_PLUGINCONFIG']._serialized_start=37
  _globals['_PLUGINCONFIG']._serialized_end=103
# @@protoc_insertion_point(module_scope)
