# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tools/socket.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12tools/socket.proto\x12\x05zorro\"v\n\x06Socket\x12\x14\n\nraw_string\x18\x01 \x01(\tH\x00\x12\x15\n\x0braw_integer\x18\x02 \x01(\x05H\x00\x12\x14\n\nraw_number\x18\x03 \x01(\x02H\x00\x12\x14\n\nraw_binary\x18\x04 \x01(\x0cH\x00\x12\x0c\n\x04\x63\x61st\x18\x05 \x01(\tB\x05\n\x03rawB%Z#github.com/Acedyn/zorro-proto/toolsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tools.socket_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z#github.com/Acedyn/zorro-proto/tools'
  _globals['_SOCKET']._serialized_start=29
  _globals['_SOCKET']._serialized_end=147
# @@protoc_insertion_point(module_scope)
